# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Bash@3
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       cd src
    #       pwd
    #       ls -l
    #       ls -l Skoruba.Duende.IdentityServer.STS.Identity/
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        buildContext: $(Build.SourcesDirectory)
        dockerfile: '**/src/Skoruba.Duende.IdentityServer.STS.Identity/Dockerfile'
        tags: |
          $(tag)
